spring:
  application:
    name: order-service


rabbitmq:
  queue:
    order:
      name: order_queue
      exchange: order_exchange
      routing_key: order_routing_key
    email:
      name: email_queue
      routing_key: email_routing_key
